config/routes.rb
Rails.application.routes.draw do
  
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :orders do
    resources:orderitems
  end

  
  devise_for :users do 
    resources :orders 
  end
  
  
  root  'static_pages#home'
  
  get 'cart/index'

  resources :items
 

  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  
  get '/cart/:id', to: 'cart#add' 
  get '/cart', to: 'cart#index'
  
  get '/clearcart', to: 'cart#clearCart'
  get '/checkout' => 'cart#createOrder'
  
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/decrease/:id' => 'cart#decrease'
  
  
  get '/login' => 'user#login' 
  get '/logout' => 'user#logout'
  
  root :to => 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  def order_params
    params.require(:order).permit( :order_date, :user_id, :status)
  end

    has_many :orderitems
    belongs_to :user
  
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :remember_me)
  end

  has_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
 before_action :authenticate_user!
 def add
    # get an id of a product
    id = params[:id]
    
    # if the cart is already been created , use the exisiting one else create a blank cart
    if session[:cart] then
        cart= session[:cart]
    else
        session[:cart]={}
        cart= session[:cart]
    end   
    
    # if product us already added increment it by one else set it to 1
    if cart[id] then
        cart[id]+=1
    else
        cart[id]=1
    end  
    
    redirect_to :action=> :index
 end   
 
 def remove
     id =params[:id]
     cart = session[:cart]
     cart.delete id
     
     redirect_to :action => :index
     
 end     
     
 def decrease
    id = params[:id] 
     cart = session[:cart]
     if cart[id]==1 then
         cart.delete id
     else
         cart[id]= cart[id]-1
    end
    redirect_to :action => :index
  end     
 
 
  def clearCart
    # sets session variable to nil and bring back to index
    session[:cart] = nil
    redirect_to :action => :index
  end
 
 
  def index
      if session[:cart] then
        @cart = session[:cart]
      else
        @cart ={}
      end  
  end
  
  def createOrder
     # Step 1: Get the current user
     @user = User.find(current_user.id)
    
     # Step 2: Create a new order and associate it with the current user
     @order = @user.orders.build(:order_date => DateTime.now, :status => 'Pending')
     @order.save
    
     # Step 3: For each item in the cart, create a new item on the order!!
     @cart = session[:cart] || {} # Get the content of the Cart
     @cart.each do | id, quantity |
         item = Item.find_by_id(id)
         @orderitem = @order.orderitems.build(:item_id => item.id, :title => item.title, :description => item.description, :quantity => quantity, :price=> item.price)
         @orderitem.save
     end
     @orders = Order.all
  end

  
  
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand)
    end
end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_date, :user_id, :status)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def login
        session[:login] = 1
        session[:cart] = nil
        flash[:notice] = "Admin Login sucessfull!!"
        redirect_to :controller => :items
    end 
    
    def logout
        session[:login] = nil
        session[:cart] = nil
        flash[:notice] = "You have been successfully logged out!!"
        redirect_to :controller => :items
    end    

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/createOrder.html.erb
<h2>Thank You</h2>
<p>You have just placed an order</p>

<div id="itemsContainer">
    <h1>Thank You<br>
    You have just placed an order <%=@orderReg.id %></h1>
</div>

<table id="customers">
    <tr>
        <% @orders.limit(1).order(id: :desc).each do |order| %>  
        <td>Order reference for the order you just placed <%= order.id %></td>
        <% end %>
    </tr>
</table>    

<table id="customers">
    <% @total = 0 %>
    <% @orderitems.each do |id,quantity| %>
      <tr>
        <% item = Orderitem.find_by_id(id) %>
       
        <td><%= item.title %></td>
        <td><%= item.quantity %></td>
        <td><%=number_to_currency(item.price, :unit => "€")%></td> 
        <td><%= number_to_currency(item.quantity * item.price, :unit => "€") %></td>
        </tr>
       
        <% timx = (item.quantity * item.price)%> 
        <% @total += timx %>
      
      </tr>
    <% end %>
    
    <tr>
       <td>Order Total: &euro; <%= @total %></td>
    </tr>
</table>

app/views/cart/index.html.erb
<%if @cart.empty?%>
<p>You cart is empty</p>
<%end%>

<p id="notice"><%= notice %></p>

<div id = "itemscontainer">
    <table id = "customers">
        <% total=0 %>
        <% @cart.each do |id, quantity|%>
        <% item= Item.find_by_id(id)%>
        <tr> 
            <td class= "image"><%= link_to (image_tag item.image_url, :style =>"height:40px"), item %></td>
            <td class = "title"><%= link_to item.title, item %></td>
            <td><a href ="/cart/remove/<%=item.id%>">Remove from cart</a></td>
            <td class = "price"><%= number_to_currency(item.price, :unit => "€" )%></td>
            <td class ="quantity"><%= quantity%>  <a href = "/cart/decrease/<%= item.id%>"> Decrease</td>
            <td class = "price"><% total_price= number_to_currency(quantity* item.price) %>
                <%= total_price %></td>
        </tr> 
        <% total += quantity *item.price %>
        <%end%>
        <tr> Grand Total: <%= number_to_currency(total, :unit => "€")%> </tr>
    </table>
    <a href = "/items" class = "button"> Continue Shopping </a>
    <a href="/clearcart" class="button">Empty Cart</a>
    <a href="/checkout" class="button">Checkout</a>
</div>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

 <div id="itemsContainer">
  
  <h1>Items</h1>
     
    <% @items.each do |item| %>
      <div class="itemhols">
       <h1><%= item.title %></h1>
       
       <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
       <p><%= item.description %></p>
       <p>Price <%= number_to_currency(item.price, :unit => "€") %>
       <br>
        Category: <%= item.category %>
       <br>
        Brand: <%= item.brand %></p>
       
       <p>
          
         <a href = "/cart/<%= item.id%>" class= "button">Add  To Cart</a>
         
         <%= link_to 'Show',  item, :class => "button", :role => "button" %>
         
         <% if session[:login] == 1 %> 
         <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
         <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
         <% end %>
       </p>
        
      </div>
    <% end %>
      
 </div>

<br>
<% if session[:login] ==1 %>
<%= link_to 'New Item',  new_item_path, :class => "button", :role => "button" %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>



 <div id="itemsContainer">
   <h1><%= @item.title %></h1>
   <%= image_tag @item.image_url, :class => 'welcomIm'  %>
       <h2><%= @item.description %></h1>
   
    <div class="itemhols">
       <p>Price <%= number_to_currency(@item.price, :unit => "€") %>
       <br>
        Category: <%= @item.category %>
        <br>
        Brand: <%= @item.brand %></p>
       
       <p>
         <%= link_to 'Back',  items_path, :class => "button", :role => "button" %>
         <%= link_to 'Edit',  edit_item_path(@item), :class => "button", :role => "button" %>
         
       </p>
        
      </div>
   
   
   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | The new Golfstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class = "headSec">
    <h1>Saturday Eve Golf club</h1>
     <ul>
     <li><%= link_to 'Home', '/' %></li> 
     <li><%= link_to 'Products', '/items' %></li>
     <li><%= link_to 'View Cart', '/cart/index' %></li>
      <li><%= link_to 'About', about_path %></li> 
      <li><%= link_to 'Help', help_path %></li> 
      
      <% if user_signed_in? %>
        <li><a href="#">Hi <%= current_user.email %></a></li>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to 'Register', new_user_registration_path %></li> 
        <li><%= link_to 'Sign in', new_user_session_path %></li>
      <% end %>
      
      <% if session[:login] == 1 %> 
        <li><%= link_to "Admin Logout", logout_path %></li>
      <% else %>
        <li><%= link_to "Admin Login", login_path %></li>
      <% end %>

      
      
     </ul>  
    </header>
    <div class ="container">
    <%= yield %>
    </div>
    
    <footer class = "foot">
      <h3>footer goes here</h3>
      
    </footer>  
    
    
  </body>
</html>

app/views/orderitems/edit.html.erb
<h1>Orderitems#edit</h1>
<p>Find me in app/views/orderitems/edit.html.erb</p>

app/views/orderitems/index.html.erb
<h1>Orderitems#index</h1>
<p>Find me in app/views/orderitems/index.html.erb</p>

app/views/orderitems/new.html.erb
<h1>Orderitems#new</h1>
<p>Find me in app/views/orderitems/new.html.erb</p>

app/views/orderitems/show.html.erb
<h1>Orderitems#show</h1>
<p>Find me in app/views/orderitems/show.html.erb</p>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_date %>
    <%= f.datetime_select :order_date %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order date</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_date %></td>
        <td><%= order.user %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order date:</strong>
  <%= @order.order_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/static_pages/about.html.erb
<%= provide(:title, "About")%>
<h1>About page</h1>
<p>coming soon</p>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help")%>
<h1>Help page</h1>
<p>you can find any help here</p>

app/views/static_pages/home.html.erb
<%= provide(:title, "Home")%>

<div class = "mainCont">
<%= image_tag("golfswing.jpg", alt:"Welcome Logo", :class => "welcomeIm")%>

<h1>Home page</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
</div>